### ISSUE TITLE
Can you provide links to evaluation datasets ?

### ISSUE THREAD

**Issue by shamanez** [kamalkraj/BioELECTRA#1]
I would love to have access to train, val, and test data splits you have used. Especially for QA tasks.

**Comment by kamalkraj** [comment]
You can download the dataset from the following link
https://microsoft.github.io/BLURB/submit.html

**Comment by shamanez** [comment]
Thanks a lot.

I found the BioASQ train, dev, and test splits from the link you sent me. 
![image](https://user-images.githubusercontent.com/16892570/122062336-6eae9d00-ce43-11eb-9c06-7eaeb1ec8bd7.png)


What about the PubmedQA ? 

Is it similar to the splits used in this[ git repository](https://github.com/pubmedqa/pubmedqa/tree/master/preprocess)?

**Comment by shamanez** [comment]
Is there any chance that you can share the pre-processed data from google drive :) ?

**Comment by kamalkraj** [comment]
PubMedQA, yes
I didn't do any specific preprocessing. Used the same script from the BLURB dataset.

**Comment by shamanez** [comment]
Thanks a lot.
